apiVersion: v1
kind: Service
metadata:
  name: kube-ingress-dns
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: ingress-dns
  ports:
    - name: dns
      port: 53
      nodePort: {{ .Values.nodePort }}
      targetPort: dns
      protocol: UDP
