apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    tool: argocd
spec:
  project: default
  info:
    - name: Description
      value: "Prepares resources ArgoCD for cluster"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  source:
    targetRevision: HEAD
    path: charts/argo-cd
    repoURL: https://github.com/wadhekarpankaj/k8s-infrastructure.git
    helm:
      values: |-
        notifications:
          enabled: false
        fullnameOverride: argocd
        dex:
          enabled: false
        server:
          clusterAdminAccess:
            enabled: true
        configs:
          cm:
            url: http://argocd.k8s.test
            users.anonymous.enabled: true
          rbac:
            create: false
          params:
            server.insecure: true
            server.logFormat: json
            server.disable.auth: true
