apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rbac
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    tool: argocd-rbac
spec:
  project: default
  info:
    - name: Description
      value: "Prepares resources ArgoCD for cluster"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  source:
    targetRevision: HEAD
    path: charts/argocd-rbac
    repoURL: https://github.com/wadhekarpankaj/k8s-infrastructure.git
    helm:
      values: |-
        default:
          role: admin
