apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    tool: argocd-apps
spec:
  project: default
  info:
    - name: Description
      value: "argocd apps"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  source:
    targetRevision: HEAD
    path: charts/argocd-apps
    repoURL: https://github.com/wadhekarpankaj/k8s-infrastructure.git
    helm:
      values: |-
        projects:
        - name: main
          additionalAnnotations:
            "helm.sh/resource-policy": keep
          destinations:
            - namespace: '*'
              server: https://kubernetes.default.svc
          sourceRepos:
            - 'https://argoproj.github.io/argo-helm'
            - 'https://github.com/wadhekarpankaj/k8s-infrastructure.git'
          clusterResourceWhitelist:
            - group: '*'
              kind: '*'
          namespaceResourceWhitelist:
            - group: '*'
              kind: '*'
          orphanedResources:
            warn: false

