apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    tool: argocd-apps
spec:
  project: default
  info:
    - name: Description
      value: "argocd apps"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  source:
    targetRevision: HEAD
    path: charts/argo-cd
    repoURL: https://github.com/wadhekarpankaj/k8s-infrastructure.git
    helm:
      values: |-
        {{- .Files.Get "configs/argocd-apps-config.yaml" | nindent 8 }}

